# Generated by Django 5.2.17 on 2026-09-23 20:50

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('water', 'Rede de agua'), ('military', 'Rede militar')], max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='ScenarioRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('topology', models.JSONField()),
                ('rules', models.JSONField(default=dict)),
                ('presentation', models.JSONField(default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('generator_version', models.CharField(default='1', max_length=64)),
                ('formulation_version', models.CharField(default='1', max_length=64)),
                ('seed', models.BigIntegerField()),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('publication_status', models.CharField(choices=[('draft', 'Rascunho'), ('solving', 'Em resolucao'), ('published', 'Publicado'), ('failed', 'Falhou')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='games.scenario')),
            ],
            options={
                'ordering': ('scenario_id', '-revision'),
            },
        ),
        migrations.CreateModel(
            name='SolverResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('optimal', 'Otimo'), ('feasible', 'Viavel'), ('infeasible', 'Inviavel'), ('no_solution', 'Sem solucao'), ('error', 'Erro')], max_length=20)),
                ('termination_reason', models.CharField(blank=True, max_length=200)),
                ('objective_value', models.FloatField(blank=True, null=True)),
                ('best_bound', models.FloatField(blank=True, null=True)),
                ('gap', models.FloatField(blank=True, null=True)),
                ('solution', models.JSONField(default=dict)),
                ('api_version', models.PositiveSmallIntegerField(default=1)),
                ('solver_name', models.CharField(blank=True, max_length=100)),
                ('solver_version', models.CharField(blank=True, max_length=100)),
                ('formulation_version', models.CharField(max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('input_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('verification_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solver_results', to='games.scenariorevision')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluida'), ('revealed', 'Solucao revelada')], db_index=True, default='active', max_length=20)),
                ('revealed', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plays', to='games.scenariorevision')),
                ('solver_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plays', to='games.solverresult')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField()),
                ('expected_version', models.PositiveIntegerField()),
                ('committed_version', models.PositiveIntegerField()),
                ('selection', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='games.play')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('play', 'request_id'), name='games_unique_attempt_request'), models.CheckConstraint(condition=models.Q(('committed_version', django.db.models.expressions.CombinedExpression(models.F('expected_version'), '+', models.Value(1)))), name='games_attempt_version_increment')],
            },
        ),
        migrations.AddConstraint(
            model_name='scenariorevision',
            constraint=models.UniqueConstraint(fields=('scenario', 'revision'), name='games_unique_scenario_revision'),
        ),
        migrations.AddConstraint(
            model_name='scenariorevision',
            constraint=models.UniqueConstraint(fields=('scenario', 'content_hash'), name='games_unique_scenario_content'),
        ),
        migrations.AddConstraint(
            model_name='scenariorevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='games_revision_gte_one'),
        ),
        migrations.AddIndex(
            model_name='solverresult',
            index=models.Index(fields=['revision', 'status', 'verified'], name='games_result_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='solverresult',
            constraint=models.CheckConstraint(condition=models.Q(('gap__isnull', True), ('gap__gte', 0), _connector='OR'), name='games_solver_gap_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['visitor_id', 'status'], name='games_play_visitor_idx'),
        ),
    ]
